name: Remote Prechecks Workflow

on: [push]

jobs:
  run-prechecks:
    runs-on: self-hosted
    #name: [self-hosted, ubuntu, X64] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Prechecks on Remote Machine
        run: |
          echo "Connecting to remote machine via SSH"
          sshpass -p "${{ secrets.UBUNTU }}" ssh -o StrictHostKeyChecking=no karthik@192.168.1.105 \
            'echo "Running commands on remote machine:" && whoami && ip a && uname -a'
