name: Deploy Docker App from GitHub Repo

on: [push]

jobs:
  deploy-app:
    runs-on: self-hosted

    steps:
      # Step 1: Run deployment script on the slave machine
      - name: Deploy App on Remote Machine
        env:
          SSH_PASSWORD: ${{ secrets.VM }}  # Secret for the slave machine password
        run: ./deploy.sh "$SSH_PASSWORD"
