name: Remote Prechecks Workflow Bash

on: [push]

jobs:
  run-prechecks:
    runs-on: self-hosted

    environment: vm  # Specify the environment where the secret is stored

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Make the bash script executable
      - name: Make script executable
        run: chmod +x bash_scripts/run_remote.sh

      # Step 3: Run the bash script
      - name: Run Prechecks on Remote Machine
        env:
          SSH_PASSWORD: ${{ secrets.VM }}  # Secret from the 'vm' environment
        run: bash bash_scripts/run_remote.sh "$SSH_PASSWORD"
