name: Remote Prechecks Workflow Bash

on: [push]

jobs:
  run-prechecks:
    runs-on: self-hosted

    environment: vm  # Specify the environment where the secret is stored

    steps:
      # Step 1: Checkout the code from your GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: Make the bash script executable
      # Note: Adjust the path to where the script is located in your repository
      - name: Make script executable
        run: chmod +x ./bash_scripts/check_remote.sh

      # Step 4: Run the bash script with the SSH password
      - name: Run Prechecks on Remote Machine
        env:
          SSH_PASSWORD: ${{ secrets.VM }}  # Secret from the 'vm' environment
        run: bash ./bash_scripts/check_remote.sh "$SSH_PASSWORD"
