name: Remote Prechecks Workflow Bash

on:
  push:
    branches:
      - Ubuntu  # Trigger workflow only on pushes to the 'Ubuntu' branch

jobs:
  run-prechecks:
    runs-on: self-hosted

    environment: vm  # Specify the environment where the secret is stored

    steps:
      # Step 1: Checkout the code from your GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x ./bash_scripts/check_remote.sh

      - name: Run Prechecks on Remote Machine
        env:
          SSH_PASSWORD: ${{ secrets.VM }}  # Secret from the 'vm' environment
        run: bash ./bash_scripts/check_remote.sh "$SSH_PASSWORD"
