name: Remote Prechecks Workflow Bash2

on:
  push:
    branches:
      - Ubuntu

jobs:
  run-prechecks:
    runs-on: self-hosted

    environment: vm

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Make Script Executable
        run: chmod +x ./bash_scripts/check_remote.sh

      - name: Debug Environment Variable
        env:
          SSH_PASSWORD: ${{ secrets.VM }}
        run: |
          echo "Password length: $(echo -n $SSH_PASSWORD | wc -c)"
          
      - name: Run Prechecks on Remote Machine
        env:
          SSH_PASSWORD: ${{ secrets.VM }}
        run: bash ./bash_scripts/check_remote.sh "$SSH_PASSWORD"
